CREATE TABLE user (
    id_user INT(5) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nama_user VARCHAR(50) DEFAULT NULL,
    email_user VARCHAR(50) DEFAULT NULL,
    password VARCHAR(255) DEFAULT NULL,
    no_hp VARCHAR(25) DEFAULT NULL
);
